# Generated by Django 6.0.2 on 2026-02-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flavor_external_id_flavor_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='shop_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
