# Generated by Django 6.0.2 on 2026-02-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flavors/'),
        ),
        migrations.AddField(
            model_name='flavor',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
