# Generated by Django 6.0.2 on 2026-02-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='flavor',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_flavor_name_per_category'),
        ),
    ]
