# Generated by Django 6.0.2 on 2026-02-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_profilecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
