# Generated by Django 6.0.2 on 2026-02-18 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavor',
            options={'ordering': ['name']},
        ),
    ]
