# Generated by Django 6.0.2 on 2026-02-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_seed_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='schema',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
