# Generated by Django 6.0.2 on 2026-02-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_banner_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Allows users to select this banner.'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates this as the global default banner.'),
        ),
    ]
