# Generated by Django 6.0.4 on 2026-04-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
