# Generated by Django 6.0.4 on 2026-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='local_image_paths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='flavor',
            name='main_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
