# Generated by Django 6.0.4 on 2026-04-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_flavor_local_image_paths_flavor_main_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drawer_anchor',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=5),
        ),
    ]
