# Generated by Django 6.0.4 on 2026-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_user_drawer_anchor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='drawer_anchor',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=5),
        ),
    ]
